/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Size = IDL.Record({
  'thickness' : IDL.Nat,
  'length' : IDL.Nat,
  'width' : IDL.Nat,
});
export const Finish = IDL.Variant({
  'honed' : IDL.Null,
  'flamed' : IDL.Null,
  'bushHammered' : IDL.Null,
  'leathered' : IDL.Null,
  'sandblasted' : IDL.Null,
  'polished' : IDL.Null,
});
export const Category = IDL.Variant({
  'granite' : IDL.Null,
  'marble' : IDL.Null,
  'exotic' : IDL.Null,
});
export const Product = IDL.Record({
  'name' : IDL.Text,
  'origin' : IDL.Text,
  'description' : IDL.Text,
  'sizes' : IDL.Vec(Size),
  'finishes' : IDL.Vec(Finish),
  'category' : Category,
});
export const CompanyInfo = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'website' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'addProduct' : IDL.Func([Product], [], []),
  'getCompanyInfo' : IDL.Func([], [CompanyInfo], ['query']),
  'getProduct' : IDL.Func([IDL.Text], [Product], ['query']),
  'getProductsByCategory' : IDL.Func([Category], [IDL.Vec(Product)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Size = IDL.Record({
    'thickness' : IDL.Nat,
    'length' : IDL.Nat,
    'width' : IDL.Nat,
  });
  const Finish = IDL.Variant({
    'honed' : IDL.Null,
    'flamed' : IDL.Null,
    'bushHammered' : IDL.Null,
    'leathered' : IDL.Null,
    'sandblasted' : IDL.Null,
    'polished' : IDL.Null,
  });
  const Category = IDL.Variant({
    'granite' : IDL.Null,
    'marble' : IDL.Null,
    'exotic' : IDL.Null,
  });
  const Product = IDL.Record({
    'name' : IDL.Text,
    'origin' : IDL.Text,
    'description' : IDL.Text,
    'sizes' : IDL.Vec(Size),
    'finishes' : IDL.Vec(Finish),
    'category' : Category,
  });
  const CompanyInfo = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'website' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'addProduct' : IDL.Func([Product], [], []),
    'getCompanyInfo' : IDL.Func([], [CompanyInfo], ['query']),
    'getProduct' : IDL.Func([IDL.Text], [Product], ['query']),
    'getProductsByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(Product)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };