/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'granite' : null } |
  { 'marble' : null } |
  { 'exotic' : null };
export interface CompanyInfo {
  'name' : string,
  'email' : string,
  'website' : string,
  'address' : string,
  'phone' : string,
}
export type Finish = { 'honed' : null } |
  { 'flamed' : null } |
  { 'bushHammered' : null } |
  { 'leathered' : null } |
  { 'sandblasted' : null } |
  { 'polished' : null };
export interface Product {
  'name' : string,
  'origin' : string,
  'description' : string,
  'sizes' : Array<Size>,
  'finishes' : Array<Finish>,
  'category' : Category,
}
export interface Size {
  'thickness' : bigint,
  'length' : bigint,
  'width' : bigint,
}
export interface _SERVICE {
  'addProduct' : ActorMethod<[Product], undefined>,
  'getCompanyInfo' : ActorMethod<[], CompanyInfo>,
  'getProduct' : ActorMethod<[string], Product>,
  'getProductsByCategory' : ActorMethod<[Category], Array<Product>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];